create or replace table VOITURE(
ID_VOITURE int PRIMARY KEY,
PLAQUE_IMMATRICULATION varchar(20) UNIQUE,
MODELE varchar(50) NOT NULL,
COULEUR varchar(20) NOT NULL,
ETAT varchar(20) NOT NULL,
URL_IMAGE varchar(50) NOT NULL,
DESCRIPTION_VOITURE varchart varchar(100) NOT NULL);

create or replace table CENTRE(
ID_CENTRE int PRIMARY KEY,
REGION varchar(20) NOT NULL,
VILLE varchar(20) NOT NULL,
ADRESSE varchar(50) NOT NULL,
CODE_POSTALE varchar(20) NOT NULL);

create or replace table CLIENT(
ID_CLIENT int AUTO_INCREMENT PRIMARY KEY,
NOM varchar(50) NOT NULL,
PRENOM varchar(50) NOT NULL,  
EMAIL varchar(50),
TELEPHONE varchar(20),
NUMERO_CB int,
Password varchar(50));

create or replace table LOCATION_VOITURE(
ID_LOCATION int AUTO_INCREMENT PRIMARY KEY,
PRIX int NOT NULL,
DATE_DEPART date NOT NULL,
DATE_ARRIVEE date,
ID_CLIENT int,
CENTRE_DEPART int NOT NULL,
CENTRE_ARRIVEE int,
FOREIGN KEY (ID_CLIENT) REFERENCES CLIENT(ID_CLIENT),
FOREIGN KEY (CENTRE_DEPART) REFERENCES CENTRE(ID_CENTRE),
FOREIGN KEY (CENTRE_ARRIVEE) REFERENCES CENTRE(ID_CENTRE));
